package blog

import "time"

/* ======================
** DO NOT EDIT THIS FILE!
** ======================
** GENERATED WITH GOMODEL
** Time: 2025-03-09T13:35:39+08:00
** Author: Gormodel
 */

type PostCategory struct {
	Id         int64     `gorm:"column:id;type:INT UNSIGNED;primaryKey;not null;autoIncrement" json:"id"`
	PostId     int64     `gorm:"column:post_id;type:INT UNSIGNED;index:idx_post;not null" json:"post_id"`
	CategoryId int64     `gorm:"column:category_id;type:INT UNSIGNED;index:idx_category;not null" json:"category_id"`
	CreatedAt  time.Time `gorm:"column:created_at;type:DATETIME;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

func post_category_id() Column[int64] {
	return "id"
}

func (s *PostCategory) ColumnId() Column[int64] {
	return post_category_id()
}

func post_category_post_id() Column[int64] {
	return "post_id"
}

func (s *PostCategory) ColumnPostId() Column[int64] {
	return post_category_post_id()
}

func post_category_category_id() Column[int64] {
	return "category_id"
}

func (s *PostCategory) ColumnCategoryId() Column[int64] {
	return post_category_category_id()
}

func post_category_created_at() Column[time.Time] {
	return "created_at"
}

func (s *PostCategory) ColumnCreatedAt() Column[time.Time] {
	return post_category_created_at()
}

func (t *PostCategory) TableName() string {
	return Schema() + ".post_category"
}
