package school

import "time"

/* ======================
** DO NOT EDIT THIS FILE!
** ======================
** GENERATED WITH GOMODEL
** Time: 2025-03-09T13:35:39+08:00
** Author: Gormodel
 */

type Course struct {
	Id          int64     `gorm:"column:id;type:INT UNSIGNED;primaryKey;not null;autoIncrement" json:"id"`
	Name        string    `gorm:"column:name;type:VARCHAR(100);size:100;index:idx_name;not null;default:''" json:"name"`
	Code        string    `gorm:"column:code;type:VARCHAR(50);size:50;uniqueIndex:uk_code;not null;default:''" json:"code"`
	Credit      float64   `gorm:"column:credit;type:DECIMAL(3,1);size:3;precision:1;not null;default:0.0" json:"credit"`
	Hours       int64     `gorm:"column:hours;type:INT UNSIGNED;not null;default:0" json:"hours"`
	Description *string   `gorm:"column:description;type:TEXT" json:"description"`
	TeacherId   int64     `gorm:"column:teacher_id;type:INT UNSIGNED;index:idx_teacher;not null;default:0" json:"teacher_id"`
	Status      int64     `gorm:"column:status;type:TINYINT;not null;default:1" json:"status"`
	CreatedAt   time.Time `gorm:"column:created_at;type:DATETIME;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:DATETIME;not null;default:CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" json:"updated_at"`
}

func course_id() Column[int64] {
	return "id"
}

func (s *Course) ColumnId() Column[int64] {
	return course_id()
}

func course_name() Column[string] {
	return "name"
}

func (s *Course) ColumnName() Column[string] {
	return course_name()
}

func course_code() Column[string] {
	return "code"
}

func (s *Course) ColumnCode() Column[string] {
	return course_code()
}

func course_credit() Column[float64] {
	return "credit"
}

func (s *Course) ColumnCredit() Column[float64] {
	return course_credit()
}

func course_hours() Column[int64] {
	return "hours"
}

func (s *Course) ColumnHours() Column[int64] {
	return course_hours()
}

func course_description() Column[*string] {
	return "description"
}

func (s *Course) ColumnDescription() Column[*string] {
	return course_description()
}

func course_teacher_id() Column[int64] {
	return "teacher_id"
}

func (s *Course) ColumnTeacherId() Column[int64] {
	return course_teacher_id()
}

func course_status() Column[int64] {
	return "status"
}

func (s *Course) ColumnStatus() Column[int64] {
	return course_status()
}

func course_created_at() Column[time.Time] {
	return "created_at"
}

func (s *Course) ColumnCreatedAt() Column[time.Time] {
	return course_created_at()
}

func course_updated_at() Column[time.Time] {
	return "updated_at"
}

func (s *Course) ColumnUpdatedAt() Column[time.Time] {
	return course_updated_at()
}

func (t *Course) TableName() string {
	return Schema() + ".course"
}
