package school

import "time"

/* ======================
** DO NOT EDIT THIS FILE!
** ======================
** GENERATED WITH GOMODEL
** Time: 2025-03-09T13:35:39+08:00
** Author: Gormodel
 */

type Enrollment struct {
	Id        int64     `gorm:"column:id;type:INT UNSIGNED;primaryKey;not null;autoIncrement" json:"id"`
	StudentId int64     `gorm:"column:student_id;type:INT UNSIGNED;index:idx_student;not null" json:"student_id"`
	CourseId  int64     `gorm:"column:course_id;type:INT UNSIGNED;index:idx_course;not null" json:"course_id"`
	Semester  string    `gorm:"column:semester;type:VARCHAR(20);size:20;index:idx_semester;not null;default:''" json:"semester"`
	Score     *float64  `gorm:"column:score;type:DECIMAL(5,2);size:5;precision:2;default:NULL COMMENT " json:"score"`
	Status    int64     `gorm:"column:status;type:TINYINT;not null;default:1" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;type:DATETIME;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:DATETIME;not null;default:CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" json:"updated_at"`
}

func enrollment_id() Column[int64] {
	return "id"
}

func (s *Enrollment) ColumnId() Column[int64] {
	return enrollment_id()
}

func enrollment_student_id() Column[int64] {
	return "student_id"
}

func (s *Enrollment) ColumnStudentId() Column[int64] {
	return enrollment_student_id()
}

func enrollment_course_id() Column[int64] {
	return "course_id"
}

func (s *Enrollment) ColumnCourseId() Column[int64] {
	return enrollment_course_id()
}

func enrollment_semester() Column[string] {
	return "semester"
}

func (s *Enrollment) ColumnSemester() Column[string] {
	return enrollment_semester()
}

func enrollment_score() Column[*float64] {
	return "score"
}

func (s *Enrollment) ColumnScore() Column[*float64] {
	return enrollment_score()
}

func enrollment_status() Column[int64] {
	return "status"
}

func (s *Enrollment) ColumnStatus() Column[int64] {
	return enrollment_status()
}

func enrollment_created_at() Column[time.Time] {
	return "created_at"
}

func (s *Enrollment) ColumnCreatedAt() Column[time.Time] {
	return enrollment_created_at()
}

func enrollment_updated_at() Column[time.Time] {
	return "updated_at"
}

func (s *Enrollment) ColumnUpdatedAt() Column[time.Time] {
	return enrollment_updated_at()
}

func (t *Enrollment) TableName() string {
	return Schema() + ".enrollment"
}
