package school

import "time"

/* ======================
** DO NOT EDIT THIS FILE!
** ======================
** GENERATED WITH GOMODEL
** Time: 2025-03-09T13:35:39+08:00
** Author: Gormodel
 */

type Student struct {
	Id        int64     `gorm:"column:id;type:INT UNSIGNED;primaryKey;not null;autoIncrement" json:"id"`
	Name      string    `gorm:"column:name;type:VARCHAR(100);size:100;index:idx_name;not null;default:''" json:"name"`
	Age       int64     `gorm:"column:age;type:INT UNSIGNED;not null;default:0" json:"age"`
	Grade     int64     `gorm:"column:grade;type:INT UNSIGNED;index:idx_grade_class;not null;default:1" json:"grade"`
	Class     int64     `gorm:"column:class;type:INT UNSIGNED;index:idx_grade_class;not null;default:1" json:"class"`
	Sex       bool      `gorm:"column:sex;type:BOOLEAN;not null;default:0" json:"sex"`
	Address   string    `gorm:"column:address;type:VARCHAR(255);size:255;not null;default:''" json:"address"`
	Phone     string    `gorm:"column:phone;type:VARCHAR(20);size:20;not null;default:''" json:"phone"`
	Email     string    `gorm:"column:email;type:VARCHAR(100);size:100;not null;default:''" json:"email"`
	CreatedAt time.Time `gorm:"column:created_at;type:DATETIME;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:DATETIME;not null;default:CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" json:"updated_at"`
}

func student_id() Column[int64] {
	return "id"
}

func (s *Student) ColumnId() Column[int64] {
	return student_id()
}

func student_name() Column[string] {
	return "name"
}

func (s *Student) ColumnName() Column[string] {
	return student_name()
}

func student_age() Column[int64] {
	return "age"
}

func (s *Student) ColumnAge() Column[int64] {
	return student_age()
}

func student_grade() Column[int64] {
	return "grade"
}

func (s *Student) ColumnGrade() Column[int64] {
	return student_grade()
}

func student_class() Column[int64] {
	return "class"
}

func (s *Student) ColumnClass() Column[int64] {
	return student_class()
}

func student_sex() Column[bool] {
	return "sex"
}

func (s *Student) ColumnSex() Column[bool] {
	return student_sex()
}

func student_address() Column[string] {
	return "address"
}

func (s *Student) ColumnAddress() Column[string] {
	return student_address()
}

func student_phone() Column[string] {
	return "phone"
}

func (s *Student) ColumnPhone() Column[string] {
	return student_phone()
}

func student_email() Column[string] {
	return "email"
}

func (s *Student) ColumnEmail() Column[string] {
	return student_email()
}

func student_created_at() Column[time.Time] {
	return "created_at"
}

func (s *Student) ColumnCreatedAt() Column[time.Time] {
	return student_created_at()
}

func student_updated_at() Column[time.Time] {
	return "updated_at"
}

func (s *Student) ColumnUpdatedAt() Column[time.Time] {
	return student_updated_at()
}

func (t *Student) TableName() string {
	return Schema() + ".student"
}
