package school

import "time"

/* ======================
** DO NOT EDIT THIS FILE!
** ======================
** GENERATED WITH GOMODEL
** Time: 2025-02-24T10:30:35+08:00
** Author: CrazyThursdayV50
 */

type Teacher struct {
	Id        int64     `gorm:"column:id;type:INT UNSIGNED;primaryKey;not null;autoIncrement" json:"id"`
	Sex       bool      `gorm:"column:sex;type:BOOLEAN;not null;default:0 COOMENT " json:"sex"`
	Age       int64     `gorm:"column:age;type:INT UNSIGNED;index:idx_age;not null;default:0" json:"age"`
	Name      string    `gorm:"column:name;type:VARCHAR(100);size:100;not null" json:"name"`
	CreatedAt time.Time `gorm:"column:created_at;type:DATETIME;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:DATETIME;not null;default:CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" json:"updated_at"`
}

func teacher_id() Column[int64] {
	return "id"
}

func (s *Teacher) ColumnId() Column[int64] {
	return teacher_id()
}

func teacher_sex() Column[bool] {
	return "sex"
}

func (s *Teacher) ColumnSex() Column[bool] {
	return teacher_sex()
}

func teacher_age() Column[int64] {
	return "age"
}

func (s *Teacher) ColumnAge() Column[int64] {
	return teacher_age()
}

func teacher_name() Column[string] {
	return "name"
}

func (s *Teacher) ColumnName() Column[string] {
	return teacher_name()
}

func teacher_created_at() Column[time.Time] {
	return "created_at"
}

func (s *Teacher) ColumnCreatedAt() Column[time.Time] {
	return teacher_created_at()
}

func teacher_updated_at() Column[time.Time] {
	return "updated_at"
}

func (s *Teacher) ColumnUpdatedAt() Column[time.Time] {
	return teacher_updated_at()
}

func (t *Teacher) TableName() string {
	return Schema() + ".teacher"
}
