CREATE TABLE `order` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `order_no` varchar(50) NOT NULL COMMENT '订单号',
  `user_id` int unsigned NOT NULL COMMENT '用户ID',
  `total_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '订单总金额',
  `payment_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '实付金额',
  `discount_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '优惠金额',
  `shipping_fee` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '运费',
  `tax_amount` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '税费',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：1-待付款，2-待发货，3-待收货，4-已完成，5-已取消，6-已退款',
  `payment_method` tinyint NOT NULL DEFAULT '1' COMMENT '支付方式：1-微信，2-支付宝，3-银行卡',
  `payment_status` tinyint NOT NULL DEFAULT '0' COMMENT '支付状态：0-未支付，1-已支付',
  `payment_time` datetime DEFAULT NULL COMMENT '支付时间',
  `shipping_status` tinyint NOT NULL DEFAULT '0' COMMENT '发货状态：0-未发货，1-已发货，2-已收货',
  `shipping_time` datetime DEFAULT NULL COMMENT '发货时间',
  `completion_time` datetime DEFAULT NULL COMMENT '完成时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `refund_time` datetime DEFAULT NULL COMMENT '退款时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  KEY `idx_user` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_payment_status` (`payment_status`),
  KEY `idx_shipping_status` (`shipping_status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci; 