CREATE TABLE `product` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL COMMENT '商品名称',
  `sku` varchar(50) NOT NULL COMMENT '商品编码',
  `description` text COMMENT '商品描述',
  `price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '售价',
  `original_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '原价',
  `cost_price` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '成本价',
  `stock` int NOT NULL DEFAULT '0' COMMENT '库存',
  `weight` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '重量(kg)',
  `category_id` int unsigned NOT NULL DEFAULT '0' COMMENT '分类ID',
  `brand_id` int unsigned NOT NULL DEFAULT '0' COMMENT '品牌ID',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT '状态：1-上架，2-下架，3-售罄，0-删除',
  `featured` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否推荐',
  `sold_count` int unsigned NOT NULL DEFAULT '0' COMMENT '销量',
  `view_count` int unsigned NOT NULL DEFAULT '0' COMMENT '浏览次数',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sku` (`sku`),
  KEY `idx_category` (`category_id`),
  KEY `idx_brand` (`brand_id`),
  KEY `idx_status` (`status`),
  KEY `idx_featured` (`featured`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci; 