package shop

import "time"

/* ======================
** DO NOT EDIT THIS FILE!
** ======================
** GENERATED WITH GOMODEL
** Time: 2025-03-09T13:35:39+08:00
** Author: Gormodel
 */

type UserAddress struct {
	Id         int64     `gorm:"column:id;type:INT UNSIGNED;primaryKey;not null;autoIncrement" json:"id"`
	UserId     int64     `gorm:"column:user_id;type:INT UNSIGNED;index:idx_user;not null" json:"user_id"`
	Name       string    `gorm:"column:name;type:VARCHAR(50);size:50;not null" json:"name"`
	Phone      string    `gorm:"column:phone;type:VARCHAR(20);size:20;not null" json:"phone"`
	Province   string    `gorm:"column:province;type:VARCHAR(50);size:50;not null" json:"province"`
	City       string    `gorm:"column:city;type:VARCHAR(50);size:50;not null" json:"city"`
	District   string    `gorm:"column:district;type:VARCHAR(50);size:50;not null" json:"district"`
	Detail     string    `gorm:"column:detail;type:VARCHAR(200);size:200;not null" json:"detail"`
	PostalCode string    `gorm:"column:postal_code;type:VARCHAR(20);size:20;not null;default:''" json:"postal_code"`
	IsDefault  int64     `gorm:"column:is_default;type:TINYINT(1);size:1;index:idx_is_default;not null;default:0" json:"is_default"`
	CreatedAt  time.Time `gorm:"column:created_at;type:DATETIME;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;type:DATETIME;not null;default:CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" json:"updated_at"`
}

func user_address_id() Column[int64] {
	return "id"
}

func (s *UserAddress) ColumnId() Column[int64] {
	return user_address_id()
}

func user_address_user_id() Column[int64] {
	return "user_id"
}

func (s *UserAddress) ColumnUserId() Column[int64] {
	return user_address_user_id()
}

func user_address_name() Column[string] {
	return "name"
}

func (s *UserAddress) ColumnName() Column[string] {
	return user_address_name()
}

func user_address_phone() Column[string] {
	return "phone"
}

func (s *UserAddress) ColumnPhone() Column[string] {
	return user_address_phone()
}

func user_address_province() Column[string] {
	return "province"
}

func (s *UserAddress) ColumnProvince() Column[string] {
	return user_address_province()
}

func user_address_city() Column[string] {
	return "city"
}

func (s *UserAddress) ColumnCity() Column[string] {
	return user_address_city()
}

func user_address_district() Column[string] {
	return "district"
}

func (s *UserAddress) ColumnDistrict() Column[string] {
	return user_address_district()
}

func user_address_detail() Column[string] {
	return "detail"
}

func (s *UserAddress) ColumnDetail() Column[string] {
	return user_address_detail()
}

func user_address_postal_code() Column[string] {
	return "postal_code"
}

func (s *UserAddress) ColumnPostalCode() Column[string] {
	return user_address_postal_code()
}

func user_address_is_default() Column[int64] {
	return "is_default"
}

func (s *UserAddress) ColumnIsDefault() Column[int64] {
	return user_address_is_default()
}

func user_address_created_at() Column[time.Time] {
	return "created_at"
}

func (s *UserAddress) ColumnCreatedAt() Column[time.Time] {
	return user_address_created_at()
}

func user_address_updated_at() Column[time.Time] {
	return "updated_at"
}

func (s *UserAddress) ColumnUpdatedAt() Column[time.Time] {
	return user_address_updated_at()
}

func (t *UserAddress) TableName() string {
	return Schema() + ".user_address"
}
